# Generated by Django 2.0.3 on 2019-02-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190202_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='background_photo',
            field=models.ImageField(upload_to='projects/img'),
        ),
    ]
