# Generated by Django 2.0 on 2019-02-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190203_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='special_class',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tech',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
