# Generated by Django 2.0 on 2019-02-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190206_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='special_class',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='tech',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
