# Generated by Django 2.0.3 on 2019-02-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190206_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_company_en',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_company_es',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_company_pt',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_project_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_project_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_project_pt',
            field=models.TextField(null=True),
        ),
    ]
