language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
script:
  - python manage.py collectstatic --noinput --settings=website.settings.travis_settings
  - python manage.py test --settings=website.settings.travis_settings
