# Generated by Django 2.0 on 2019-02-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Strength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_icon', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('special_class', models.CharField(blank=True, default='', max_length=64, null=True)),
            ],
        ),
    ]
