# Generated by Django 2.0.3 on 2019-02-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strength',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='strength',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='strength',
            name='description_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='strength',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='strength',
            name='title_es',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='strength',
            name='title_pt',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
